### ISSUE TITLE
stop method

### ISSUE THREAD

**Issue by TrySound** [jbraithwaite/scroll-to-y#1]
I'd like to stop scrolling on mousewheel on some keys down. Can you return a method or object with method stop for it?

Scrolling can be simply canceled with `cancelAnimationFrame` and `clearTimeout`.

**Comment by jbraithwaite** [comment]
Hey, a little swamped, I'll gladly integrate this. If you want to submit a PR, I'll merge it, if not, give me a few days and I'll code this up.
